### ISSUE TITLE
 NRSC-5-D released

### ISSUE THREAD

**Issue by rafael2k** [argilo/gr-nrsc5#1]
http://www.nrscstandards.org/NRSC-5-D.asp

**Comment by argilo** [comment]
@rafael2k Thanks for letting me know about that! I'll have a look over it to see if anything needs to be changed in gr-nrsc5.

**Comment by rafael2k** [comment]
; ))
Thanks for your great contribution to the free software world!

**Comment by argilo** [comment]
I didn't spot any changes relevant to this project. But I did update the README and some references in f277223e10a5e71d7b7a2d045385ae07ba8b30f1, so I'll close this issue now.
