### ISSUE TITLE
Build fails for gr3.9 and fix

### ISSUE THREAD

**Issue by ferrellsl** [argilo/gr-nrsc5#10]
The NRSC 5 build will fail under the latest gnuradio source code on github (3.9).  I was able to get around this problem and also add rtl-sdr (gr-osmosdr) support by doing the following:

Gnuradio 3.9 with NRSC5, UHD, and rtl-sdr support.

Build instructions:

Install Gnuradio build prerequisistes:

sudo apt install git cmake g++ libboost-all-dev libgmp-dev swig python3-numpy \
python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev libcomedi-dev \
libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python3-pyqt5 \
liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins

Download Gnuradio from github and build:

git clone --recursive https://github.com/gnuradio/gnuradio.git
Build with CMake:

$ cd gnuradio
$ mkdir build
$ cd build
$ cmake [OPTIONS] ../
$ make
$ make test
$ sudo make install
$ sudo ldconfig

Add NRSC5 support:

clone from:  https://github.com/argilo/gr-nrsc5

Edit the cmakelists.txt file to look for gr3.9 instead of gr3.8

mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

Build gr-osmosdr:

Download gr-osomsdr for gr3.8 here:  https://github.com/igorauad/gr-osmosdr/tree/gr3.8

Edit the cmakelists.txt to look for gr3.9 instead of gr3.8

mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig

I hope this helps others who have been struggling with this because pybombs fails miserably right now when trying to build gr3.9 with rtl-sdr support and NRSC5.

**Comment by argilo** [comment]
I'll see about changing the master branch of gr-nrsc5 to call for GNU Radio 3.9 now that GNU Radio has updated its master branch with that version number.

In the meantime, I'd recommend using the stable maint-3.8 branches of both GNU Radio and gr-nrsc5.

**Comment by argilo** [comment]
Fixed in d410d387d434028b77b740c58802ff367b0ddda1.
