### ISSUE TITLE
Build fail Cmake 

### ISSUE THREAD

**Issue by AIRWORLDPREMIUM** [argilo/gr-nrsc5#12]
unfortunately 

--------------------------------------------------------------------------------------------------------

canning dependencies of target fdk_aac_external
[  3%] Creating directories for 'fdk_aac_external'
[  7%] Performing download step (git clone) for 'fdk_aac_external'
Cloning into 'fdk_aac_external'...
Note: checking out '3b63dab59416a629f3de82463eb3875319a086d5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3b63dab Disable intensity stereo for HDC.
[ 11%] No patch step for 'fdk_aac_external'
[ 15%] No update step for 'fdk_aac_external'
[ 19%] Performing configure step for 'fdk_aac_external'
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:20: installing './compile'
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for library containing sin... -lm
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating fdk-aac.pc
config.status: executing depfiles commands
config.status: executing libtool commands
[ 23%] Performing build step for 'fdk_aac_external'
  CXX      libAACdec/src/aacdec_drc.lo
  CXX      libAACdec/src/aacdec_hcr.lo
  CXX      libAACdec/src/aacdecoder.lo
  CXX      libAACdec/src/aacdec_pns.lo
  CXX      libAACdec/src/aac_ram.lo
  CXX      libAACdec/src/block.lo
  CXX      libAACdec/src/channelinfo.lo
  CXX      libAACdec/src/ldfiltbank.lo
  CXX      libAACdec/src/rvlcbit.lo
  CXX      libAACdec/src/rvlc.lo
  CXX      libAACdec/src/aacdec_hcr_bit.lo
  CXX      libAACdec/src/aacdec_hcrs.lo
  CXX      libAACdec/src/aacdecoder_lib.lo
  CXX      libAACdec/src/aacdec_tns.lo
  CXX      libAACdec/src/aac_rom.lo
  CXX      libAACdec/src/channel.lo
  CXX      libAACdec/src/conceal.lo
  CXX      libAACdec/src/pulsedata.lo
  CXX      libAACdec/src/rvlcconceal.lo
  CXX      libAACdec/src/stereo.lo
  CXX      libAACenc/src/aacenc.lo
  CXX      libAACenc/src/aacEnc_ram.lo
  CXX      libAACenc/src/band_nrg.lo
  CXX      libAACenc/src/block_switch.lo
  CXX      libAACenc/src/grp_data.lo
  CXX      libAACenc/src/metadata_main.lo
  CXX      libAACenc/src/pre_echo_control.lo
  CXX      libAACenc/src/quantize.lo
  CXX      libAACenc/src/tonality.lo
  CXX      libAACenc/src/aacEnc_rom.lo
  CXX      libAACenc/src/bandwidth.lo
  CXX      libAACenc/src/channel_map.lo
  CXX      libAACenc/src/intensity.lo
  CXX      libAACenc/src/ms_stereo.lo
  CXX      libAACenc/src/psy_configuration.lo
  CXX      libAACenc/src/sf_estim.lo
  CXX      libAACenc/src/transform.lo
  CXX      libAACenc/src/aacenc_lib.lo
  CXX      libAACenc/src/aacenc_tns.lo
  CXX      libAACenc/src/bit_cnt.lo
  CXX      libAACenc/src/chaosmeasure.lo
  CXX      libAACenc/src/line_pe.lo
  CXX      libAACenc/src/noisedet.lo
  CXX      libAACenc/src/psy_main.lo
  CXX      libAACenc/src/spreading.lo
  CXX      libAACenc/src/aacenc_pns.lo
  CXX      libAACenc/src/adj_thr.lo
  CXX      libAACenc/src/bitenc.lo
  CXX      libAACenc/src/dyn_bits.lo
  CXX      libAACenc/src/metadata_compressor.lo
  CXX      libAACenc/src/pnsparam.lo
  CXX      libAACenc/src/qc_main.lo
  CXX      libMpegTPDec/src/tpdec_adif.lo
  CXX      libMpegTPDec/src/tpdec_adts.lo
  CXX      libMpegTPDec/src/tpdec_asc.lo
  CXX      libMpegTPDec/src/tpdec_drm.lo
  CXX      libMpegTPDec/src/tpdec_latm.lo
  CXX      libMpegTPDec/src/tpdec_lib.lo
  CXX      libMpegTPEnc/src/tpenc_adif.lo
  CXX      libMpegTPEnc/src/tpenc_adts.lo
  CXX      libMpegTPEnc/src/tpenc_asc.lo
  CXX      libMpegTPEnc/src/tpenc_latm.lo
  CXX      libMpegTPEnc/src/tpenc_lib.lo
  CXX      libSBRdec/src/env_calc.lo
  CXX      libSBRdec/src/env_dec.lo
  CXX      libSBRdec/src/env_extr.lo
  CXX      libSBRdec/src/huff_dec.lo
  CXX      libSBRdec/src/lpp_tran.lo
  CXX      libSBRdec/src/psbitdec.lo
  CXX      libSBRdec/src/psdec.lo
  CXX      libSBRdec/src/psdec_hybrid.lo
  CXX      libSBRdec/src/sbr_crc.lo
  CXX      libSBRdec/src/sbr_deb.lo
  CXX      libSBRdec/src/sbr_dec.lo
  CXX      libSBRdec/src/sbrdec_drc.lo
  CXX      libSBRdec/src/sbrdec_freq_sca.lo
  CXX      libSBRdec/src/sbrdecoder.lo
  CXX      libSBRdec/src/sbr_ram.lo
  CXX      libSBRdec/src/sbr_rom.lo
  CXX      libSBRenc/src/bit_sbr.lo
  CXX      libSBRenc/src/env_bit.lo
  CXX      libSBRenc/src/fram_gen.lo
  CXX      libSBRenc/src/mh_det.lo
  CXX      libSBRenc/src/ps_bitenc.lo
  CXX      libSBRenc/src/ps_encode.lo
  CXX      libSBRenc/src/resampler.lo
  CXX      libSBRenc/src/sbr_encoder.lo
  CXX      libSBRenc/src/sbr_ram.lo
  CXX      libSBRenc/src/ton_corr.lo
  CXX      libSBRenc/src/code_env.lo
  CXX      libSBRenc/src/env_est.lo
  CXX      libSBRenc/src/invf_est.lo
  CXX      libSBRenc/src/nf_est.lo
  CXX      libSBRenc/src/ps_main.lo
  CXX      libSBRenc/src/sbrenc_freq_sca.lo
  CXX      libSBRenc/src/sbr_misc.lo
  CXX      libSBRenc/src/sbr_rom.lo
  CXX      libSBRenc/src/tran_det.lo
  CXX      libPCMutils/src/limiter.lo
  CXX      libPCMutils/src/pcmutils_lib.lo
  CXX      libFDK/src/autocorr2nd.lo
  CXX      libFDK/src/dct.lo
  CXX      libFDK/src/FDK_bitbuffer.lo
  CXX      libFDK/src/FDK_core.lo
  CXX      libFDK/src/FDK_crc.lo
  CXX      libFDK/src/FDK_hybrid.lo
  CXX      libFDK/src/FDK_tools_rom.lo
  CXX      libFDK/src/FDK_trigFcts.lo
  CXX      libFDK/src/fft.lo
  CXX      libFDK/src/fft_rad2.lo
  CXX      libFDK/src/fixpoint_math.lo
  CXX      libFDK/src/mdct.lo
  CXX      libFDK/src/qmf.lo
  CXX      libFDK/src/scale.lo
  CXX      libSYS/src/cmdl_parser.lo
  CXX      libSYS/src/conv_string.lo
  CXX      libSYS/src/genericStds.lo
  CXX      libSYS/src/wav_file.lo
  GEN      libfdk-aac.la
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
[ 26%] Performing install step for 'fdk_aac_external'
 /bin/mkdir -p '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib'
 /bin/bash ./libtool   --mode=install /usr/bin/install -c   libfdk-aac.la '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib'
libtool: install: /usr/bin/install -c .libs/libfdk-aac.lai /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/libfdk-aac.la
libtool: install: /usr/bin/install -c .libs/libfdk-aac.a /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/libfdk-aac.a
libtool: install: chmod 644 /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/libfdk-aac.a
libtool: install: ranlib /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/libfdk-aac.a
libtool: finish: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin" ldconfig -n /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib
----------------------------------------------------------------------
Libraries have been installed in:
   /home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/include/fdk-aac'
 /usr/bin/install -c -m 644 ./libSYS/include/machine_type.h ./libSYS/include/genericStds.h ./libSYS/include/FDK_audio.h ./libAACenc/include/aacenc_lib.h ./libAACdec/include/aacdecoder_lib.h '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/include/fdk-aac'
 /bin/mkdir -p '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/pkgconfig'
 /usr/bin/install -c -m 644 fdk-aac.pc '/home/airworldpremium/gr-nrsc5/build/fdk-aac-prefix/lib/pkgconfig'
[ 30%] Completed 'fdk_aac_external'
[ 30%] Built target fdk_aac_external
Scanning dependencies of target gnuradio-nrsc5
[ 34%] Building CXX object lib/CMakeFiles/gnuradio-nrsc5.dir/hdc_encoder_impl.cc.o
[ 38%] Building CXX object lib/CMakeFiles/gnuradio-nrsc5.dir/l1_fm_encoder_impl.cc.o
[ 42%] Building CXX object lib/CMakeFiles/gnuradio-nrsc5.dir/l2_encoder_impl.cc.o
[ 46%] Building CXX object lib/CMakeFiles/gnuradio-nrsc5.dir/psd_encoder_impl.cc.o
[ 50%] Building CXX object lib/CMakeFiles/gnuradio-nrsc5.dir/sis_encoder_impl.cc.o
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/liborc-0.4.so', needed by 'lib/libgnuradio-nrsc5.so.v1.0.0-4-g55983c08'.  Stop.
CMakeFiles/Makefile2:172: recipe for target 'lib/CMakeFiles/gnuradio-nrsc5.dir/all' failed
make[1]: *** [lib/CMakeFiles/gnuradio-nrsc5.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by argilo** [comment]
It looks like you're missing the liborc package for your operating system. Please install that and try again. If you're still having trouble, let me know.
