### ISSUE TITLE
Fail to install on GNURadio 3.8

### ISSUE THREAD

**Issue by viktorivan** [argilo/gr-nrsc5#18]
Hi, I am installing gr-nrsc5, but I have an error because it is looking for gr-3.9 instead of gr-3.8. The installation its through PyBOMBS.

[WARNING] Configuration failed. Re-trying with higher verbosity.
-- PyBOMBS installed GNU Radio. Setting CMAKE_INSTALL_PREFIX to /home/ivan/Software/gr-3.8
CMake Error at CMakeLists.txt:77 (find_package):
  Could not find a configuration file for package "Gnuradio" that is
  compatible with requested version "3.9".

  The following configuration files were considered but not accepted:

    /home/ivan/Software/gr-3.8/lib/cmake/gnuradio/GnuradioConfig.cmake, version: 3.8.2.git

-- Configuring incomplete, errors occurred!
See also "/home/ivan/Software/gr-3.8/src/gr-nrsc5/build/CMakeFiles/CMakeOutput.log".
[ERROR] Configuration failed after running at least twice.
[ERROR] Problem occurred while building package gr-nrsc5:
Configuration failed
[ERROR] Error installing package gr-nrsc5. Aborting.

Regards

**Comment by argilo** [comment]
You'll need to check out the maint-3.8 branch to build with GNU Radio 3.8. Try the following:
```
cd /home/ivan/Software/gr-3.8/src/gr-nrsc5
git checkout maint-3.8
pybombs rebuild gr-nrsc5
```

**Comment by viktorivan** [comment]
Its works, thanks
