### ISSUE TITLE
Station Name (Call Sign)

### ISSUE THREAD

**Issue by tsalisbury0** [argilo/gr-nrsc5#19]
Apparently Station Name Long is transmitted as message ID 0010 and Station Name Short is Message ID 0001 as seen here:
[1020s.pdf](https://github.com/argilo/gr-nrsc5/files/6071666/1020s.pdf)

**Comment by argilo** [comment]
It would definitely be good to add other messages to the SIS encoder. Currently it only encodes "Station Name – short format" messages:

https://github.com/argilo/gr-nrsc5/blob/master/lib/sis_encoder_impl.cc

I don't have any immediate plans to work on this, but contributions are welcome.

**Comment by tsalisbury0** [comment]
> It would definitely be good to add other messages to the SIS encoder. Currently it only encodes "Station Name – short format" messages:
> 
> https://github.com/argilo/gr-nrsc5/blob/master/lib/sis_encoder_impl.cc
> 
> I don't have any immediate plans to work on this, but contributions are welcome.

Based on experience with the long name, it can't be used when the short name is encoded. It's an either or situation.

My Insignia displays Long Names but the Visteon remains blank as Short isn't transmitted.

![20201230_224030.jpg](https://user-images.githubusercontent.com/16229948/109766738-30ef7680-7bbc-11eb-82ce-d625759760cc.jpg)
![20201230_224309.jpg](https://user-images.githubusercontent.com/16229948/109766747-364cc100-7bbc-11eb-89dc-ec74add7d27d.jpg)

**Comment by argilo** [comment]
The specification indicates that "Station Name - long format" is "Not recommended for new designs."

Universal Short Station Name (MSG ID 1000) seems to be its replacement.

**Comment by tsalisbury0** [comment]
> The specification indicates that "Station Name - long format" is "Not recommended for new designs."
> 
> Universal Short Station Name (MSG ID 1000) seems to be its replacement.

The latest station to add long name is The Breeze in Philadelphia. Washington DC has one. Richmond has one.

**Comment by argilo** [comment]
There's also this note:

> Must have message content that is identical to Station Slogan

I presume modern receivers use Station Slogan instead of Station Name - long format.

**Comment by tsalisbury0** [comment]
> There's also this note:
> 
> > Must have message content that is identical to Station Slogan
> 
> I presume modern receivers use Station Slogan instead of Station Name - long format.

My HDR-14 supports long name but only displays the first 4 characters of it. My Insignia radios display all of it.

**Comment by tsalisbury0** [comment]
![20210510_164507](https://user-images.githubusercontent.com/16229948/117732396-6cf31900-b1b5-11eb-9285-b41bc5244176.jpg)
Maine Public is one. I can send an IQ if needed of one Sideband

**Comment by argilo** [comment]
An I/Q file captured using [nrsc5](https://github.com/theori-io/nrsc5)'s `-w` option would be helpful.

**Comment by argilo** [comment]
The SIS encoder now supports long station name, as well as all the other messages types (with the exception of emergency alerts), so I'll close this off.
