### ISSUE TITLE
AttributeError: 'module' object has no attribute 'sis_encoder' 

### ISSUE THREAD

**Issue by jowijo** [argilo/gr-nrsc5#3]
When attempting to run the hackrf flowgraph, this error is presented.
```
Using HackRF One with firmware 2017.02.1 
Traceback (most recent call last):
  File "/home/hd_tx_hackrf.py", line 202, in <module>
    main()
  File "/home/hd_tx_hackrf.py", line 190, in main
    tb = top_block_cls()
  File "/home//hd_tx_hackrf.py", line 101, in __init__
    self.nrsc5_sis_encoder_0 = nrsc5.sis_encoder('KTST')
AttributeError: 'module' object has no attribute 'sis_encoder'
```
All nrsc-5 blocks and code are installed to `/usr/local/lib` (symlinked to /usr/lib), and the osmosdr works fine.

**Comment by argilo** [comment]
If you're seeing that error, then you probably haven't installed gr-nrsc5 correctly. Either use pybombs, or else run the following:
```
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
```

**Comment by argilo** [comment]
If your GNU Radio is in `/usr` rather than `/usr/local`, then replace the `cmake ..` command with `cmake -DCMAKE_INSTALL_PREFIX=/usr ..`.

**Comment by jowijo** [comment]
Interesting, looks like changing the cmake prefix worked. Thanks.

**Comment by argilo** [comment]
@jowijo I'm glad to hear you got it working.

I've updated the README with build instructions including the alternate cmake prefix.
