### ISSUE TITLE
advice tunnig. 

### ISSUE THREAD

**Issue by Toei79** [argilo/gr-nrsc5#34]
its possible convert those to stream links?

 im getting Hd radio signals then i using a flask server to try to stream to tivimate, it plays , but only on pc.  takes time to load one to other.  using icecast2. for get stream link and ffmpeg.

**Comment by argilo** [comment]
Unfortunately I don't understand what you're asking. What do you want converted to stream links? What are you using gr-nrsc5 for?

**Comment by argilo** [comment]
It sounds like your question is about the nrsc5 project (https://github.com/theori-io/nrsc5), not the gr-nrsc5 project. I'll close off this issue, since it appears to be unrelated to gr-nrsc5.
