### ISSUE TITLE
Linking with non-standard install fails.

### ISSUE THREAD

**Issue by drmpeg** [argilo/gr-nrsc5#4]
On a regular source build (cmake, make, etc) with GNU Radio installed in a custom directory (in my case, /opt/gnuradio-3.7.12git), the linker fails with:

/usr/bin/ld: cannot find -lgnuradio-fec

This can be fixed by using set(GR_REQUIRED_COMPONENTS) instead of target_link_libraries().

In CMakelists.txt change:

set(GR_REQUIRED_COMPONENTS RUNTIME)

to:

set(GR_REQUIRED_COMPONENTS RUNTIME FEC)

and delete -lgnuradio-fec from lib/CMakelists.txt

**Comment by argilo** [comment]
Thanks for the bug report, @drmpeg! I made the suggested change in 1d61d8aafbd6180396d600d286152aa4cb46cd0f. Does it build properly for you now?

**Comment by drmpeg** [comment]
Wunderbar.
