### ISSUE TITLE
Feed MPX Audio to analog part and delay it

### ISSUE THREAD

**Issue by veso266** [argilo/gr-nrsc5#5]
Hi I tried transmitting HD Radio and Sony XDR-F1HD decodes it fine. I have used your example flowgraph and modified it a bit to accept MPX Audio which Stereo Tool is generating: https://github.com/veso266/MPX-Signal-Modulator/blob/master/IBOC/HD-Radio-TX.grc

but analog audio is too fast and when switching to digital there is 1-2 seconds of delay so I am wondering how can I slow analog part of audio down so there will be no delay when switching to Digital version?
and for some reason Digital part is a bit louder then analog one
PS: How can I transmitt only Digital Audio without Analog?

Thanks for Anwsering and Best Regards

**Comment by argilo** [comment]
You could use a Delay block in GNU Radio to delay the analog audio enough to match the digital. And you can use a Multiply Const block to adjust the audio level.

gr-nrsc5 does not yet support digital-only modes. I took a stab at it once, but didn't manage to get it working with the receivers I had on hand.
