### ISSUE TITLE
Is it possible to use it in a comunity radio?

### ISSUE THREAD

**Issue by hydrosIII** [argilo/gr-nrsc5#7]
Hi, Im currently implementing a small community radio in Mexico. Internet radio is easy to make it work, but your project seems that it makes possible for making cheap encoder. Here in Mexico we use the IBOC format for digital radio. Is it possible to use this project to make a transmitter and attach it to the FM band?

**Comment by argilo** [comment]
@hydrosIII I'm not aware of anyone who has used gr-nrsc5 for that purpose, but gr-nrsc5 is capable of generating an IBOC signal (in the HD Radio / NRSC-5 format) which could be used on the FM band. Please note that I don't offer any support for this project, so if adaptations are necessary you'd have to make them yourself. Also, some parts of the NRSC-5 standard are encumbered by patents, so there may be legal implications to using gr-nrsc5.

**Comment by hydrosIII** [comment]
So, it is more a legal issue than a technical one? Right. Thanks.

**Comment by argilo** [comment]
Yes, that's correct.
