### ISSUE TITLE
Create a release tag for distribution integration

### ISSUE THREAD

**Issue by repk** [argilo/gr-nrsc5#9]
Hi,

First of all thanks for this project, it has been really useful. I am trying to integrate it in xbps package manager (https://github.com/void-linux/void-packages/pull/4563). It would be nice and easier if it were a release tag to use.

Could it be done or is it to soon ?

Thanks in advance

**Comment by argilo** [comment]
The project is in a stable state, so I've created a `v1.0.0` tag: https://github.com/argilo/gr-nrsc5/releases/tag/v1.0.0

Let me know if there's anything else you need.

**Comment by repk** [comment]
Perfect, thanks a lot.
